# You need to execute this update several times to fix all wrong dates.
# Before you need to change virtuoso.ini:
#
#   MaxVectorSize         = 10000000
#   MaxQueryExecutionTime = 0

PREFIX wikibase: <http://wikiba.se/ontology-beta#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE { ?subject wikibase:timeValue ?oldDate }
INSERT { ?subject wikibase:timeValue ?newDate }
WHERE {
  SELECT *
  WHERE {
    ?subject wikibase:timeValue ?oldDate
    FILTER ( strStarts(str(?oldDate), "+"))
    BIND (strDT(strAfter(str(?oldDate), "+"), xsd:dateTime) AS ?newDate)
  }
  LIMIT 400000
}
