# Query 1
# US presidents and wives
# Original source: https://www.mediawiki.org/wiki/Wikibase/Indexing/SPARQL_Query_Examples#US_presidents_and_spouses
# 1) n-ary predicates
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
SELECT ?p ?pl ?ppicture ?w ?wl ?wpicture
WHERE {
  wd:Q30 p:P6 [ ps:P6 ?p ] .
  ?p p:P26 [ ps:P26 ?w ] .
  OPTIONAL  { ?p rdfs:label ?pl . filter (lang(?pl) = "en") . }
  OPTIONAL { ?w rdfs:label ?wl . filter (lang(?wl) = "en"). }
  OPTIONAL {
    ?p p:P18 [ ps:P18 ?ppicture ] .
    ?w p:P18 [ ps:P18 ?wpicture ] .
  }
}
LIMIT 10
