# Query 2
# Politicians who died of cancer (of any type)
# Original source: https://www.mediawiki.org/wiki/Wikibase/Indexing/SPARQL_Query_Examples#Politicians_who_died_of_cancer_.28of_any_type.29
# 2) RDF reification
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?politician ?cause ?politician_label ?cause_of_death_label {
  [] rdf:subject ?politician ; rdf:predicate wd:P106 ; rdf:object wd:Q82955 .	# find items that have "occupation (P106): politician (Q82955)"	
  [] rdf:subject ?politician ; rdf:predicate wd:P509 ; rdf:object ?cause .		# with a P509 (cause of death) claim
  [] rdf:subject ?cause ; rdf:predicate wd:P279 ; rdf:object wd:Q12078 .        # ... where the cause is a !!direct!! subclass of (P279*) cancer (Q12078)
																				# !!no property paths in reification!!

  OPTIONAL  {  
    ?politician rdfs:label ?politician_label . filter (lang(?politician_label) = "en") . 
	?cause rdfs:label ?cause_of_death_label . filter (lang(?cause_of_death_label) = "en") . 
  }
}