# Query 4
# What is the relation between Terrell Buckley and Miami Dolphins?
# Original source: https://www.mediawiki.org/wiki/Wikibase/Indexing/SPARQL_Query_Examples#What_is_the_relation_between_Terrell_Buckley_and_Miami_Dolphins.3F
# 2) RDF reification
PREFIX wikibase: <http://wikiba.se/ontology-beta#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?l
WHERE
{
	[] rdf:subject wd:Q5571382 ; rdf:predicate ?p ; rdf:object wd:Q223243 .
	?p a wikibase:Property .
	?p rdfs:label ?l . FILTER (lang(?l) = "en")
}
LIMIT 10
