# Query 8
# Population in Europe after 1960
# Original source: https://www.mediawiki.org/wiki/Wikibase/Indexing/SPARQL_Query_Examples#Population_in_Europe_after_1960
# 2) RDF reification
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT  ?objectLabel    (YEAR(?date) as ?year) 
        ?population     (?objectLabel as ?Location)
WHERE
{
		[] rdf:subject ?object ; rdf:predicate wd:P31 ; rdf:object wd:Q185441 .
		?populationStatement rdf:subject ?object ; rdf:predicate wd:P1082 ; rdf:object ?population ; wd:P585 ?date .
		OPTIONAL { ?object rdfs:label ?objectLabel . FILTER(lang(?objectLabel)='en') }   
	FILTER (YEAR(?date) >= 1960)
} 
ORDER BY ?objectLabel ?year